#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$SCRIPT_DIR/.db-backup.env"
RUN_SCRIPT="$SCRIPT_DIR/run-db-backup.sh"
COMPOSE_FILE_DEFAULT="$SCRIPT_DIR/docker-compose.prod.yml"
CRON_TAG="# taskflow-db-backup"
LOG_FILE="$SCRIPT_DIR/logs/db-backup.log"

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local value

  if [[ -n "$default_value" ]]; then
    read -r -p "$label [$default_value]: " value
    printf '%s\n' "${value:-$default_value}"
  else
    while true; do
      read -r -p "$label: " value
      if [[ -n "$value" ]]; then
        printf '%s\n' "$value"
        return
      fi
      echo "This value is required."
    done
  fi
}

prompt_secret() {
  local label="$1"
  local value

  while true; do
    read -r -s -p "$label: " value
    echo
    if [[ -n "$value" ]]; then
      printf '%s\n' "$value"
      return
    fi
    echo "This value is required."
  done
}

shell_quote() {
  printf "%q" "$1"
}

normalize_endpoint() {
  case "$1" in
    http://*|https://*) printf '%s\n' "$1" ;;
    *) printf 'https://%s\n' "$1" ;;
  esac
}

load_env_default() {
  local key="$1"
  local env_file="$SCRIPT_DIR/.env"

  if [[ -f "$env_file" ]]; then
    awk -F= -v key="$key" '
      $0 !~ /^[[:space:]]*#/ && $1 == key {
        value = substr($0, index($0, "=") + 1)
        gsub(/^["'\''"]|["'\''"]$/, "", value)
        print value
        exit
      }
    ' "$env_file"
  fi
}

if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is required before installing database backups." >&2
  exit 1
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required before installing database backups." >&2
  exit 1
fi

if ! command -v crontab >/dev/null 2>&1; then
  echo "crontab is required before installing the daily schedule." >&2
  exit 1
fi

if [[ ! -f "$RUN_SCRIPT" ]]; then
  echo "Backup runner not found: $RUN_SCRIPT" >&2
  exit 1
fi

chmod 700 "$RUN_SCRIPT"

echo "Taskflow PostgreSQL daily backup installer"
echo
echo "This installs a server-local cron job for 03:00 every day."
echo "Current server time: $(date)"
echo "Current timezone: $(date +%Z) ($(date +%z))"
echo

compose_file="$(prompt "Docker Compose file" "$COMPOSE_FILE_DEFAULT")"
postgres_service="$(prompt "Postgres service name" "postgres")"
postgres_user_default="$(load_env_default POSTGRES_USER)"
postgres_db_default="$(load_env_default POSTGRES_DB)"
postgres_user="$(prompt "Postgres user" "${postgres_user_default:-taskflow}")"
postgres_db="$(prompt "Postgres database" "${postgres_db_default:-taskflow}")"
backup_prefix="$(prompt "R2 object prefix" "postgres")"

echo
echo "R2 backup bucket settings"
r2_endpoint="$(normalize_endpoint "$(prompt "R2 endpoint, e.g. <account-id>.r2.cloudflarestorage.com")")"
r2_bucket="$(prompt "R2 bucket name, e.g. taskflow-db-backups")"
r2_region="$(prompt "R2 region" "auto")"
r2_access_key_id="$(prompt "R2 access key id")"
r2_secret_access_key="$(prompt_secret "R2 secret access key")"

mkdir -p "$SCRIPT_DIR/backups/tmp" "$SCRIPT_DIR/backups/postgres" "$SCRIPT_DIR/logs"
chmod 700 "$SCRIPT_DIR/backups" "$SCRIPT_DIR/backups/tmp" "$SCRIPT_DIR/backups/postgres" "$SCRIPT_DIR/logs"

umask 077
{
  echo "# Generated by infra/install-db-backup-cron.sh on $(date -Is)"
  echo "COMPOSE_FILE=$(shell_quote "$compose_file")"
  echo "POSTGRES_SERVICE=$(shell_quote "$postgres_service")"
  echo "POSTGRES_USER=$(shell_quote "$postgres_user")"
  echo "POSTGRES_DB=$(shell_quote "$postgres_db")"
  echo "BACKUP_PREFIX=$(shell_quote "$backup_prefix")"
  echo "LOCAL_BACKUP_DIR=$(shell_quote "$SCRIPT_DIR/backups")"
  echo "LOCAL_KEEP_COUNT=3"
  echo "R2_ENDPOINT=$(shell_quote "$r2_endpoint")"
  echo "R2_BUCKET=$(shell_quote "$r2_bucket")"
  echo "R2_REGION=$(shell_quote "$r2_region")"
  echo "R2_ACCESS_KEY_ID=$(shell_quote "$r2_access_key_id")"
  echo "R2_SECRET_ACCESS_KEY=$(shell_quote "$r2_secret_access_key")"
} > "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

cron_command="0 3 * * * cd $(shell_quote "$ROOT_DIR") && $(shell_quote "$RUN_SCRIPT") >> $(shell_quote "$LOG_FILE") 2>&1 $CRON_TAG"
tmp_cron="$(mktemp)"
cleanup() {
  rm -f "$tmp_cron"
}
trap cleanup EXIT

crontab -l 2>/dev/null | grep -vF "$CRON_TAG" > "$tmp_cron" || true
echo "$cron_command" >> "$tmp_cron"
crontab "$tmp_cron"

echo
echo "Installed daily database backup cron:"
echo "$cron_command"
echo
echo "Private config: $CONFIG_FILE"
echo "Log file: $LOG_FILE"
echo "Local backups: $SCRIPT_DIR/backups/postgres"
echo
read -r -p "Run one test backup now? [y/N]: " run_test
case "$run_test" in
  y|Y|yes|YES)
    "$RUN_SCRIPT"
    ;;
  *)
    echo "Skipped test backup. You can run it later with: $RUN_SCRIPT"
    ;;
esac

cat <<EOF

R2 lifecycle reminder:
- Configure the R2 bucket to delete objects under "$backup_prefix/" after 35 days.
- Keep this bucket separate from user attachments.

Restore sanity check example:
  docker run --rm -v "$SCRIPT_DIR/backups/postgres:/backup:ro" postgres:16-alpine pg_restore --list "/backup/<dump-file>" >/dev/null

Cron check:
  crontab -l | grep taskflow-db-backup
EOF
